-- AlterTable
ALTER TABLE "session_bookings"
ADD COLUMN IF NOT EXISTS "total_amount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "deposit_amount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "balance_amount" INTEGER NOT NULL DEFAULT 0;
